# Generated by Django 3.0.5 on 2020-04-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseseupdates', '0002_case_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='date',
        ),
    ]
